// <auto-generated />
using GeoSense.API.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GeoSense.API.Migrations
{
    [DbContext(typeof(GeoSenseContext))]
    [Migration("20250926002623_RemoveAlocacaoMotoeDefeito")]
    partial class RemoveAlocacaoMotoeDefeito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CHASSI");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA");

                    b.Property<string>("ProblemaIdentificado")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PROBLEMA_IDENTIFICADO");

                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("VagaId")
                        .IsUnique();

                    b.ToTable("MOTO", (string)null);
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Patio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("PATIO", (string)null);
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Vaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PATIO_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.HasIndex("Numero", "PatioId")
                        .IsUnique();

                    b.ToTable("VAGA", (string)null);
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Moto", b =>
                {
                    b.HasOne("GeoSense.API.Infrastructure.Persistence.Vaga", "Vaga")
                        .WithMany("Motos")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Vaga", b =>
                {
                    b.HasOne("GeoSense.API.Infrastructure.Persistence.Patio", "Patio")
                        .WithMany("Vagas")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Patio", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("GeoSense.API.Infrastructure.Persistence.Vaga", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
